blank_issues_enabled: false
contact_links:
  - name: ask in discussions
    url: https://github.com/okandship/MODELDROP/discussions/categories/%E1%9A%B1meta
    about: (preferred)
  - name: dm on x
    url: https://x.com/okandship
    about: okandship
  - name: email
    url: https://mail.google.com/mail/?to=okandship@gmail.com&tf=cm
    about: okandship@gmail.com
